name: 'Deploy Hardcoded HTML to Pages'
description: 'Deploys the deploy_html folder directly to GitHub Pages'

runs:
  using: "composite"
  steps:
    - name: Setup GitHub Pages
      uses: actions/configure-pages@v5
      with:
        enablement: true

    - name: Upload HTML Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # Hardcoded to the folder containing your demo.html
        path: './.github/action/deploy_html/demo.html'

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
