name: Call Actions Example

on:
  workflow_dispatch:

# Mandatory permissions for GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  demonstrate-actions:
    runs-on: ubuntu-latest
    
    # environment:
    #   name: github-pages
    #   url: ${{ steps.deploy_custom.outputs.page_url }}demo.html # Appended demo.html to the URL
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Calls your local action, which uses the hardcoded path automatically
      - name: Run hardcoded deployment action
        id: deploy_custom
        uses: ./.github/action/deploy_html
